rails_server/config/routes.rb
Rails.application.routes.draw do
  resources :speedforce_users

  root 'speedforce_users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails_server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_server/app/models/speedforce_user.rb
class SpeedforceUser < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :emergency_contact_name, presence: true
  validates :emergency_contact_phone, presence: true
  validates :emergency_contact_email, presence: true
end

rails_server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails_server/app/controllers/speedforce_users_controller.rb
class SpeedforceUsersController < ApplicationController
  before_action :set_speedforce_user, only: %i[ show edit update destroy ]

  # GET /speedforce_users or /speedforce_users.json
  def index
    @speedforce_users = SpeedforceUser.all
  end

  # GET /speedforce_users/1 or /speedforce_users/1.json
  def show
  end

  # GET /speedforce_users/new
  def new
    @speedforce_user = SpeedforceUser.new
  end

  # GET /speedforce_users/1/edit
  def edit
  end

  # POST /speedforce_users or /speedforce_users.json
  def create
    @speedforce_user = SpeedforceUser.new(speedforce_user_params)

    respond_to do |format|
      if @speedforce_user.save
        format.html { redirect_to @speedforce_user, notice: "Speedforce user was successfully created." }
        format.json { render :show, status: :created, location: @speedforce_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @speedforce_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speedforce_users/1 or /speedforce_users/1.json
  def update
    respond_to do |format|
      if @speedforce_user.update(speedforce_user_params)
        format.html { redirect_to @speedforce_user, notice: "Speedforce user was successfully updated." }
        format.json { render :show, status: :ok, location: @speedforce_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @speedforce_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speedforce_users/1 or /speedforce_users/1.json
  def destroy
    @speedforce_user.destroy
    respond_to do |format|
      format.html { redirect_to speedforce_users_url, notice: "Speedforce user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speedforce_user
      @speedforce_user = SpeedforceUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def speedforce_user_params
      params.require(:speedforce_user).permit(:name, :phone, :email, :emergency_contact_name, :emergency_contact_phone, :emergency_contact_email, :force, :speed, :latitude, :longitude)
    end
end

rails_server/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_server/app/helpers/speedforce_users_helper.rb
module SpeedforceUsersHelper
end

rails_server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsServer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_server/app/views/speedforce_users/_form.html.erb
<%= form_with(model: speedforce_user) do |form| %>
  <% if speedforce_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(speedforce_user.errors.count, "error") %> prohibited this speedforce_user from being saved:</h2>

      <ul>
        <% speedforce_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :emergency_contact_name %>
    <%= form.text_field :emergency_contact_name %>
  </div>

  <div class="field">
    <%= form.label :emergency_contact_phone %>
    <%= form.text_field :emergency_contact_phone %>
  </div>

  <div class="field">
    <%= form.label :emergency_contact_email %>
    <%= form.text_field :emergency_contact_email %>
  </div>

  <div class="field">
    <%= form.label :force %>
    <%= form.text_field :force %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.text_field :speed %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails_server/app/views/speedforce_users/edit.html.erb
<h1>Editing Speedforce User</h1>

<%= render 'form', speedforce_user: @speedforce_user %>

<%= link_to 'Show', @speedforce_user %> |
<%= link_to 'Back', speedforce_users_path %>

rails_server/app/views/speedforce_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Speedforce Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Emergency contact name</th>
      <th>Emergency contact phone</th>
      <th>Emergency contact email</th>
      <th>Force</th>
      <th>Speed</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @speedforce_users.each do |speedforce_user| %>
      <tr>
        <td><%= speedforce_user.name %></td>
        <td><%= speedforce_user.phone %></td>
        <td><%= speedforce_user.email %></td>
        <td><%= speedforce_user.emergency_contact_name %></td>
        <td><%= speedforce_user.emergency_contact_phone %></td>
        <td><%= speedforce_user.emergency_contact_email %></td>
        <td><%= speedforce_user.force %></td>
        <td><%= speedforce_user.speed %></td>
        <td><%= speedforce_user.latitude %></td>
        <td><%= speedforce_user.longitude %></td>
        <td><%= link_to 'Show', speedforce_user %></td>
        <td><%= link_to 'Edit', edit_speedforce_user_path(speedforce_user) %></td>
        <td><%= link_to 'Destroy', speedforce_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Speedforce User', new_speedforce_user_path %>

rails_server/app/views/speedforce_users/new.html.erb
<h1>New Speedforce User</h1>

<%= render 'form', speedforce_user: @speedforce_user %>

<%= link_to 'Back', speedforce_users_path %>

rails_server/app/views/speedforce_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @speedforce_user.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @speedforce_user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @speedforce_user.email %>
</p>

<p>
  <strong>Emergency contact name:</strong>
  <%= @speedforce_user.emergency_contact_name %>
</p>

<p>
  <strong>Emergency contact phone:</strong>
  <%= @speedforce_user.emergency_contact_phone %>
</p>

<p>
  <strong>Emergency contact email:</strong>
  <%= @speedforce_user.emergency_contact_email %>
</p>

<p>
  <strong>Force:</strong>
  <%= @speedforce_user.force %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @speedforce_user.speed %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @speedforce_user.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @speedforce_user.longitude %>
</p>

<%= link_to 'Edit', edit_speedforce_user_path(@speedforce_user) %> |
<%= link_to 'Back', speedforce_users_path %>